
spring.datasource.url=jdbc:postgresql://localhost:5432/db?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto = create

spring.sql.init.platform = init
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode = always

# Configuration Gemini
gemini.api.key=AIzaSyDytkpheq5ZDZpwvTe1Y7WC8f6q9h1l8Zk
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent